const data = [
  {
    _id: '64f389465ae26083f39b189e',
    bodyPart: 'chest',
    equipment: 'dumbbell',
    gifUrl: 'https://ftp.goit.study/img/power-pulse/gifs/0302.gif',
    name: 'dumbbell decline fly',
    target: 'pectorals',
    description:
      'These are the large chest muscles responsible for shoulder adduction and horizontal adduction. Bench press, push-ups, and chest flies target these muscles.',
    rating: 4,
    burnedCalories: 67,
    time: 3,
    popularity: 3643,
  },
  {
    _id: '64f389465ae26083f39b18bb',
    bodyPart: 'chest',
    equipment: 'dumbbell',
    gifUrl: 'https://ftp.goit.study/img/power-pulse/gifs/0331.gif',
    name: 'dumbbell incline twisted flyes',
    target: 'pectorals',
    description:
      'These are the large chest muscles responsible for shoulder adduction and horizontal adduction. Bench press, push-ups, and chest flies target these muscles.',
    rating: 4.67,
    burnedCalories: 70,
    time: 3,
    popularity: 362,
  },
  {
    _id: '64f389465ae26083f39b1824',
    bodyPart: 'chest',
    equipment: 'cable',
    gifUrl: 'https://ftp.goit.study/img/power-pulse/gifs/0151.gif',
    name: 'cable bench press',
    target: 'pectorals',
    description:
      'These are the large chest muscles responsible for shoulder adduction and horizontal adduction. Bench press, push-ups, and chest flies target these muscles.',
    rating: 3,
    burnedCalories: 188,
    time: 3,
    popularity: 87,
  },
  {
    _id: '64f389465ae26083f39b19bb',
    bodyPart: 'chest',
    equipment: 'body weight',
    gifUrl: 'https://ftp.goit.study/img/power-pulse/gifs/0659.gif',
    name: 'push-up (wall)',
    target: 'pectorals',
    description:
      'These are the large chest muscles responsible for shoulder adduction and horizontal adduction. Bench press, push-ups, and chest flies target these muscles.',
    rating: 4.72,
    burnedCalories: 38,
    time: 3,
    popularity: 436,
  },
  {
    _id: '64f389465ae26083f39b18b1',
    bodyPart: 'chest',
    equipment: 'dumbbell',
    gifUrl: 'https://ftp.goit.study/img/power-pulse/gifs/0321.gif',
    name: 'dumbbell incline hammer press',
    target: 'pectorals',
    description:
      'These are the large chest muscles responsible for shoulder adduction and horizontal adduction. Bench press, push-ups, and chest flies target these muscles.',
    rating: 3,
    burnedCalories: 273,
    time: 3,
    popularity: 106,
  },
  {
    _id: '64f389465ae26083f39b1aa6',
    bodyPart: 'chest',
    equipment: 'medicine ball',
    gifUrl: 'https://ftp.goit.study/img/power-pulse/gifs/1303.gif',
    name: 'medicine ball chest push from 3 point stance',
    target: 'pectorals',
    description:
      'These are the large chest muscles responsible for shoulder adduction and horizontal adduction. Bench press, push-ups, and chest flies target these muscles.',
    rating: 3,
    burnedCalories: 173,
    time: 3,
    popularity: 73,
  },
  {
    _id: '64f389465ae26083f39b1aaa',
    bodyPart: 'chest',
    equipment: 'bosu ball',
    gifUrl: 'https://ftp.goit.study/img/power-pulse/gifs/1307.gif',
    name: 'push up on bosu ball',
    target: 'pectorals',
    description:
      'These are the large chest muscles responsible for shoulder adduction and horizontal adduction. Bench press, push-ups, and chest flies target these muscles.',
    rating: 3,
    burnedCalories: 259,
    time: 3,
    popularity: 54,
  },
  {
    _id: '64f389465ae26083f39b1aaf',
    bodyPart: 'chest',
    equipment: 'medicine ball',
    gifUrl: 'https://ftp.goit.study/img/power-pulse/gifs/1312.gif',
    name: 'medicine ball chest push with run release',
    target: 'pectorals',
    description:
      'These are the large chest muscles responsible for shoulder adduction and horizontal adduction. Bench press, push-ups, and chest flies target these muscles.',
    rating: 3,
    burnedCalories: 238,
    time: 3,
    popularity: 72,
  },
  {
    _id: '64f389465ae26083f39b19b8',
    bodyPart: 'chest',
    equipment: 'stability ball',
    gifUrl: 'https://ftp.goit.study/img/power-pulse/gifs/0655.gif',
    name: 'push-up (on stability ball)',
    target: 'pectorals',
    description:
      'These are the large chest muscles responsible for shoulder adduction and horizontal adduction. Bench press, push-ups, and chest flies target these muscles.',
    rating: 3,
    burnedCalories: 196,
    time: 3,
    popularity: 36,
  },
  {
    _id: '64f389465ae26083f39b19f4',
    bodyPart: 'chest',
    equipment: 'smith machine',
    gifUrl: 'https://ftp.goit.study/img/power-pulse/gifs/0758.gif',
    name: 'smith incline reverse-grip press',
    target: 'pectorals',
    description:
      'These are the large chest muscles responsible for shoulder adduction and horizontal adduction. Bench press, push-ups, and chest flies target these muscles.',
    rating: 3,
    burnedCalories: 171,
    time: 3,
    popularity: 50,
  },
  {
    _id: '64f389465ae26083f39b19f4',
    bodyPart: 'chest',
    equipment: 'smith machine',
    gifUrl: 'https://ftp.goit.study/img/power-pulse/gifs/0758.gif',
    name: 'smith incline reverse-grip press',
    target: 'pectorals',
    description:
      'These are the large chest muscles responsible for shoulder adduction and horizontal adduction. Bench press, push-ups, and chest flies target these muscles.',
    rating: 3,
    burnedCalories: 171,
    time: 3,
    popularity: 50,
  },
  {
    _id: '64f389465ae26083f39b19f4',
    bodyPart: 'chest',
    equipment: 'smith machine',
    gifUrl: 'https://ftp.goit.study/img/power-pulse/gifs/0758.gif',
    name: 'smith incline reverse-grip press',
    target: 'pectorals',
    description:
      'These are the large chest muscles responsible for shoulder adduction and horizontal adduction. Bench press, push-ups, and chest flies target these muscles.',
    rating: 3,
    burnedCalories: 171,
    time: 3,
    popularity: 50,
  },
  {
    _id: '64f389465ae26083f39b19f4',
    bodyPart: 'chest',
    equipment: 'smith machine',
    gifUrl: 'https://ftp.goit.study/img/power-pulse/gifs/0758.gif',
    name: 'smith incline reverse-grip press',
    target: 'pectorals',
    description:
      'These are the large chest muscles responsible for shoulder adduction and horizontal adduction. Bench press, push-ups, and chest flies target these muscles.',
    rating: 3,
    burnedCalories: 171,
    time: 3,
    popularity: 50,
  },
];

export default data;
